version: "3.5"
services:
  log-reader:
    build: ./log-reader
    volumes:
      - shared-logs:/logs
    depends_on:
      - summarizer
    image: log-reader.logreader.public.dappnode.eth:0.1.0
  summarizer:
    build: ./summarizer
    volumes:
      - shared-logs:/logs
    image: summarizer.logreader.public.dappnode.eth:0.1.0
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - shared-logs:/logs
    depends_on:
      - summarizer
    image: frontend.logreader.public.dappnode.eth:0.1.0
volumes:
  shared-logs: {}
